using System.Text.Json.Nodes;
using ATLAS.Kernel.JsonEngine.Graph.Interfaces;
using ATLAS.Kernel.JsonEngine.SQL;
using ATLAS.Kernel.JsonEngine.SQL.Interfaces;

namespace ATLAS.Kernel.JsonEngine.AI;

/// <summary>
/// Executes AI QUERY pipelines over JSON data, SQL-like JSON queries, and graph ranking operations.
/// </summary>
/// <remarks>
/// The pipeline supports <c>FIND</c>, <c>THEN GRAPH EXPAND</c>, <c>THEN RANK BY PAGERANK</c>, and <c>RETURN</c> steps.
/// </remarks>
/// <example>
/// Execute a pipeline generated by <see cref="JsonAiNl"/>:
/// <code>
/// var root = JsonCore.Parse(jsonText)!;
///
/// var graph = new JsonGraph();
/// graph.Build(root, "$.items", "id", "dependencias");
///
/// var sqlEngine = new JsonSqlEngine();
/// var aiQuery = JsonAiNl.ToAiQuery("items caros por importancia con id y nombre");
///
/// var rows = JsonAiEngine.Execute(root, graph, aiQuery, sqlEngine);
/// </code>
/// </example>
public static class JsonAiEngine
{
    /// <summary>
    /// Executes an AI QUERY pipeline and returns the projected rows.
    /// </summary>
    /// <param name="root">The JSON document root used by <c>FIND</c> steps.</param>
    /// <param name="graph">The graph used by graph expansion and PageRank ranking steps.</param>
    /// <param name="aiQuery">The AI QUERY pipeline text to execute.</param>
    /// <param name="sqlEngine">The SQL-like JSON query engine used to execute <c>FIND</c> steps.</param>
    /// <returns>A list of projected rows keyed by the fields requested in the <c>RETURN</c> step.</returns>
    /// <example>
    /// <code>
    /// var result = JsonAiEngine.Execute(
    ///     root,
    ///     graph,
    ///     """
    ///     AI QUERY:
    ///       FIND items WHERE precio.valor &gt; 50
    ///       RETURN id, nombre, precio.valor
    ///     """,
    ///     new JsonSqlEngine());
    /// </code>
    /// </example>
    public static List<Dictionary<string, JsonNode?>> Execute(JsonNode root, IJsonGraph graph, string aiQuery, IJsonSqlEngine sqlEngine)
    {
        List<string> lines = aiQuery
                    .Split(new[] { "\r\n", "\n" }, StringSplitOptions.RemoveEmptyEntries)
            .Select(l => l.Trim())
            .Where(l => !string.IsNullOrWhiteSpace(l) && !l.StartsWith("AI QUERY", StringComparison.OrdinalIgnoreCase))
            .ToList();

        var data = new List<JsonSqlRow>();
        List<Dictionary<string, JsonNode?>>? result = null;

        foreach (string line in lines)
        {
            if (line.StartsWith("FIND", StringComparison.OrdinalIgnoreCase))
            {
                data = StepFind(root, line, sqlEngine);
            }
            else if (line.Contains("GRAPH EXPAND", StringComparison.OrdinalIgnoreCase))
            {
                data = StepGraphExpand(graph, data, line);
            }
            else if (line.Contains("RANK BY", StringComparison.OrdinalIgnoreCase))
            {
                data = StepRank(graph, data, line);
            }
            else if (line.Contains("ORDER BY", StringComparison.OrdinalIgnoreCase))
            {
                data = StepOrderBy(data, line);
            }
            else if (line.Contains("LIMIT", StringComparison.OrdinalIgnoreCase))
            {
                data = StepLimit(data, line);
            }
            else if (line.StartsWith("RETURN", StringComparison.OrdinalIgnoreCase))
            {
                result = StepReturn(data, line);
            }
        }

        return result ?? new List<Dictionary<string, JsonNode?>>();
    }

    private static List<JsonSqlRow> StepFind(JsonNode root, string line, IJsonSqlEngine sqlEngine)
    {
        string afterFind = line[4..].Trim();
        string path;
        string? where = null;
        int whereIdx = afterFind.IndexOf("WHERE", StringComparison.OrdinalIgnoreCase);

        if (whereIdx >= 0)
        {
            path = afterFind[..whereIdx].Trim();
            where = afterFind[(whereIdx + 5)..].Trim();
        }
        else
        {
            path = afterFind;
        }

        string sql = where is null
            ? $"SELECT * FROM $.{path}[*]"
            : $"SELECT * FROM $.{path}[*] WHERE {where}";

        return sqlEngine.Execute(root, sql);
    }
    private static List<JsonSqlRow> StepGraphExpand(IJsonGraph graph, List<JsonSqlRow> data, string line)
    {
        // "THEN GRAPH EXPAND dependencias[*] UP TO 3 LEVELS"
        int upToIdx = line.IndexOf("UP TO", StringComparison.OrdinalIgnoreCase);
        int levels = 1;

        if (upToIdx >= 0)
        {
            string? levelsStr = line[(upToIdx + 5)..]
                .Trim()
                .Split(' ', StringSplitOptions.RemoveEmptyEntries)
                .FirstOrDefault();

            if (!int.TryParse(levelsStr, out levels))
                levels = 1;
        }

        var result = new List<JsonSqlRow>();
        var added = new HashSet<string>();

        foreach (JsonSqlRow row in data)
        {
            JsonNode? node = GetRowNode(graph, row);
            if (node is null)
                continue;

            string? id = JsonCore.GetString(node, "id");
            if (id is null)
                continue;

            AddNode(result, graph, id, added, node, true);

            List<string> expanded = Expand(graph, id, levels);
            foreach (string expandedId in expanded)
            {
                    AddNode(result, graph, expandedId, added);
            }
        }

        return result;
    }

    private static void AddNode(List<JsonSqlRow> result, IJsonGraph graph, string id, HashSet<string> added, JsonNode? fallbackNode = null, bool isSeed = false)
    {
        if (!added.Add(id)) return;

        JsonNode? node = graph.Nodes.TryGetValue(id, out JsonNode? graphNode)
            ? graphNode
            : fallbackNode;

        if (node is null)
        {
            return;
        }

        var row = new JsonSqlRow { ["value"] = node };
        if (isSeed)
            row["__seed"] = JsonValue.Create(true);
        result.Add(row);
    }

    private static List<string> Expand(IJsonGraph graph, string startId, int levels)
    {
        var visited = new HashSet<string> { startId };
        var frontier = new List<string> { startId };
        var result = new List<string>();

        for (int lvl = 0; lvl < levels; lvl++)
        {
            var next = new List<string>();
            foreach (string id in frontier)
            {
                if (!graph.Edges.TryGetValue(id, out var children)) continue;
                foreach (string c in children.Where(visited.Add))
                {
                    next.Add(c);
                    result.Add(c);
                }
            }
            frontier = next;
            if (frontier.Count == 0) break;
        }

        return result;
    }

    private static List<JsonSqlRow> StepRank(IJsonGraph graph, List<JsonSqlRow> data, string line)
    {
        // "RANK BY PAGERANK"
        string method = line[(line.IndexOf("BY", StringComparison.OrdinalIgnoreCase) + 2)..].Trim();
        if (!method.Equals("PAGERANK", StringComparison.OrdinalIgnoreCase))
            return data;

        static string NormalizeId(string k)
        {
            if (string.IsNullOrEmpty(k)) return k;
            if (k.Length >= 2 && k.StartsWith("\"") && k.EndsWith("\""))
                return k[1..^1];
            return k;
        }

        // Build normalized node list and reversed adjacency (dependency -> dependent)
        List<string> normNodes = graph.Nodes.Keys.Select(NormalizeId).ToList();
        int n = normNodes.Count;
        var revEdges = new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase);
        foreach (string k in normNodes)
            revEdges[k] = new List<string>();

        foreach (KeyValuePair<string, List<string>> kv in graph.Edges)
        {
            string parent = NormalizeId(kv.Key);
            foreach (string child in kv.Value.Select(NormalizeId))
            {
                if (!revEdges.ContainsKey(child))
                    revEdges[child] = new List<string>();
                revEdges[child].Add(parent); // child (dependency) -> parent (dependent)
            }
        }

        // Detect seed nodes (rows marked by StepGraphExpand)
        var seedSet = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (JsonSqlRow row in data)
        {
            if (!row.TryGetValue("__seed", out JsonNode? seedNode) || seedNode is null)
            {
                continue;
            }

            JsonNode? rn = GetRowNode(graph, row);
            string? nid = rn is not null ? JsonCore.GetString(rn, "id") : null;
            if (string.IsNullOrEmpty(nid) && row.TryGetValue("id", out JsonNode? idNode) && idNode is not null)
            {
                if (idNode is JsonValue jv && jv.TryGetValue(out string? s)) nid = s;
                else
                {
                    string tmp = idNode.ToString();
                    nid = tmp.Length >= 2 && tmp.StartsWith("\"") && tmp.EndsWith("\"") ? tmp[1..^1] : tmp;
                }
            }
            if (!string.IsNullOrEmpty(nid))
                seedSet.Add(NormalizeId(nid));
        }

        Dictionary<string, double> rank = normNodes.ToDictionary(k => k, _ => 1.0 / Math.Max(1, n));
        Dictionary<string, double> newRank = normNodes.ToDictionary(k => k, _ => 0.0);
        const double damping = 0.85;
        const int iterations = 20;

        for (int it = 0; it < iterations; it++)
        {
            if (seedSet.Count > 0)
            {
                foreach (string k in normNodes)
                    newRank[k] = (1 - damping) * (seedSet.Contains(k) ? 1.0 / seedSet.Count : 0.0);
            }
            else
            {
                foreach (string k in normNodes)
                    newRank[k] = (1 - damping) / Math.Max(1, n);
            }

            foreach (string id in normNodes)
            {
                List<string> dependents = revEdges.TryGetValue(id, out List<string>? lst) ? lst : new List<string>();
                if (dependents.Count == 0)
                    continue;
                double share = rank[id] / dependents.Count;
                foreach (string dep in dependents.Where(newRank.ContainsKey))
                    newRank[dep] += damping * share;
            }

            foreach (string k in normNodes)
                rank[k] = newRank[k];
        }

        return data
            .OrderByDescending(r =>
            {
                JsonNode? node = GetRowNode(graph, r);
                string? id = JsonCore.GetString(node, "id");
                if (id is not null)
                {
                    return rank.GetValueOrDefault(NormalizeId(id), 0.0);
                }

                if (!r.TryGetValue("id", out JsonNode? idNode) || idNode is null)
                    return 0.0;
                if (idNode is JsonValue jv && jv.TryGetValue(out string? s))
                    id = s;
                else
                {
                    string tmp = idNode.ToString();
                    id = tmp.Length >= 2 && tmp.StartsWith("\"") && tmp.EndsWith("\"") ? tmp[1..^1] : tmp;
                }
                return rank.GetValueOrDefault(NormalizeId(id), 0.0);
            })
            .ToList();
    }

    private static List<JsonSqlRow> StepOrderBy(List<JsonSqlRow> data, string line)
    {
        int byIdx = line.IndexOf("ORDER BY", StringComparison.OrdinalIgnoreCase);
        string after = byIdx >= 0 ? line[(byIdx + "ORDER BY".Length)..].Trim() : line.Trim();
        string[] parts = after.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        string field = parts.Length > 0 ? parts[0] : "";
        string dir = parts.Length > 1 ? parts[1].ToUpperInvariant() : "ASC";

        Func<JsonSqlRow, double?> getNum = row =>
        {
            if (row.TryGetValue(field, out JsonNode? v) && v is JsonValue jv && jv.TryGetValue(out double dv))
                return dv;
            if (row.TryGetValue("value", out JsonNode? node) && node is not null)
            {
                double? d = JsonCore.GetDouble(node, field);
                if (d.HasValue) return d.Value;
            }
            if (row.TryGetValue(field, out JsonNode? v2) && v2 != null && double.TryParse(v2.ToString().Trim('"'), out double parsed))
                return parsed;
            return null;
        };

        Func<JsonSqlRow, string?> getStr = row =>
        {
            if (row.TryGetValue(field, out JsonNode? v) && v != null)
                return v.ToString();
            if (row.TryGetValue("value", out JsonNode? node) && node is not null && JsonCore.Get(node, field) is { } n2)
                return n2.ToString();
            return null;
        };

        bool anyNum = data.Any(r => getNum(r).HasValue);
        if (anyNum)
        {
            return dir == "DESC"
                ? data.OrderByDescending(r => getNum(r) ?? double.MinValue).ToList()
                : data.OrderBy(r => getNum(r) ?? double.MinValue).ToList();
        }
        return dir == "DESC"
            ? data.OrderByDescending(r => getStr(r) ?? string.Empty, StringComparer.OrdinalIgnoreCase).ToList()
            : data.OrderBy(r => getStr(r) ?? string.Empty, StringComparer.OrdinalIgnoreCase).ToList();
    }

    private static List<JsonSqlRow> StepLimit(List<JsonSqlRow> data, string line)
    {
        int idx = line.IndexOf("LIMIT", StringComparison.OrdinalIgnoreCase);

        if (idx < 0)
        {
            return data;
        }
        string limStr = line[(idx + "LIMIT".Length)..].Trim();

        return int.TryParse(limStr, out int lim) ? data.Take(lim).ToList() : data;
    }

    private static List<Dictionary<string, JsonNode?>> StepReturn(List<JsonSqlRow> data, string line)
    {
        // "RETURN id, nombre" or "RETURN *"
        string fieldsStr = line[6..].Trim();
        string[] fields = fieldsStr.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        var result = new List<Dictionary<string, JsonNode?>>();

        foreach (JsonSqlRow row in data)
        {
            row.TryGetValue("value", out JsonNode? node);
            var outRow = new Dictionary<string, JsonNode?>();

            foreach (string f in fields)
            {
                if (f == "*")
                {
                    outRow["*"] = node ?? row.GetValueOrDefault("value");
                }
                else
                {
                    JsonNode? value = node is not null ? JsonCore.Get(node, f) : row.GetValueOrDefault(f);
                    outRow[f] = value;
                }
            }

            result.Add(outRow);
        }

        return result;
    }

    private static JsonNode? GetRowNode(IJsonGraph graph, JsonSqlRow row)
    {
        if (row.TryGetValue("value", out JsonNode? value) && value is not null)
            return value;
        if (!row.TryGetValue("id", out JsonNode? idNode) || idNode is null)
            return null;

        string id;

        if (idNode is JsonValue jv && jv.TryGetValue<string>(out var s))
            id = s;
        else
        {
            string tmp = idNode.ToString();
            id = tmp.StartsWith("\"") && tmp.EndsWith("\"") && tmp.Length >= 2 ? tmp[1..^1] : tmp;
        }

        return graph.Nodes.GetValueOrDefault(id);
    }
}
